server:
  port: 8081
#spring.datasource.url=jdbc:mysql://192.168.56.101:23306/testSpringSecurity?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
# spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testspringsecurity?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: demo示例
  redis:
    host: 192.168.56.101
    database: 0
    port: 6379
    password: null
    timeout: 3000
    jedis:
      pool:
        max-active: 1000
        max-idle: 10
        max-wait: 10000
        min-idle: 5
        time-between-eviction-runs: 30000
    lettuce:
      shutdown-timeout: 100ms
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0整合Demo
  try-host: http://localhost:${server.port}


